"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
console.log('Addition');
console.log('1 + 7 = ' + (1 + 7));
console.log('\nSubtraction');
console.log('9 - 1 = ' + (9 - 1));
console.log('\nMultiplication');
console.log('2 * 4 = ' + (2 * 4));
console.log('\nDivision');
console.log('16 / 2 = ' + (16 / 2));
